[package]
name = "kumo-server-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = {path="../config"}
data-loader = {path="../data-loader"}
domain-map = {path="../domain-map"}
json_comments = "0.2"
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
mod-amqp = {path="../mod-amqp"}
mod-dns-resolver = {path="../mod-dns-resolver"}
mod-http = {path="../mod-http"}
mod-memoize = {path="../mod-memoize"}
mod-redis = {path="../mod-redis"}
mod-sqlite = {path="../mod-sqlite"}
serde_json = "1.0"
throttle = {path="../throttle"}
tokio = {version="1.25", features=["full", "tracing"]}
toml = "0.7"
