[package]
name = "mod-sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = {path="../config"}
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
serde_json = "1.0"
sqlite = "0.31"
tokio = {workspace=true, features=["rt", "tracing"]}
