[package]
name = "kumo-log-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounce-classify = {path="../bounce-classify"}
chrono = {version="0.4", features=["serde"]}
message = {path="../message"}
rfc5321 = {path="../rfc5321"}
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
