[package]
name = "kumo-log-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13"
bounce-classify = {path="../bounce-classify"}
chrono = {version="0.4", default-features=false, features=["serde", "std"]}
mailparse = "0.14"
#message = {path="../message"}
rfc5321 = {path="../rfc5321"}
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"

[dev-dependencies]
k9 = "0.11"
