[package]
name = "traffic-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = {version="4.1", features=["derive"]}
num-format = "0.4"
rand = "0.8"
rfc5321 = {path="../rfc5321"}
tokio = {version="1.25", features=["full"]}
uuid = {version="1.3", features=["v4", "rng"]}
