kind: pipeline
name: rust

steps:
- name: test
  image: rust:latest
  commands:
  - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  - apt update
  - ./get-deps.sh
  - mkdir -p ~/.cargo/bin
  - curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ~/.cargo/bin
  #- cargo install cargo-nextest --locked
  - cargo build --verbose --release
  - cargo nextest run --release
