kind: pipeline
name: rust
type: docker

steps:
- name: cache
  image: rust:latest
  volumes:
  - name: cache
    path: /tmp/build-cache
  commands:
  - ls -l /tmp/build-cache
  - echo hello
  - echo HOME is $HOME
  - false

- name: restore-build-cache
  image: meltwater/drone-cache
  volumes:
  - name: cache
    path: /tmp/cache
  settings:
    backend: "filesystem"
    restore: true
    cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
    archive_format: "gzip"
    mount:
      - ~/.cargo/registry/index/
      - ~/.cargo/registry/cache/
      - ~/.cargo/git/db/      

- name: test
  image: rust:latest
  commands:
  - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  - apt update
  - ./get-deps.sh
  - cargo install cargo-nextest --locked
  - cargo build --verbose --release
  - cargo nextest run --release

- name: update-build-cache
  image: meltwater/drone-cache
  volumes:
  - name: cache
    path: /tmp/cache
  settings:
    backend: "filesystem"
    rebuild: true
    cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
    archive_format: "gzip"
    mount:
      - ~/.cargo/registry/index/
      - ~/.cargo/registry/cache/
      - ~/.cargo/git/db/      

volumes:
  - name: cache
    host:
      path: /var/lib/drone-build-cache

---
kind: pipeline
name: ubuntu-22
type: docker

steps:
- name: build
  image: ubuntu:22.04
  commands:
  - false
  - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  - apt update
  - apt install -y curl git
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - . $HOME/.cargo/env
  - ./get-deps.sh
  - cargo install cargo-nextest --locked
  - cargo build --verbose --release
  - cargo nextest run --release
  - ./assets/build-deb.sh

