[workspace]
members = [
  "crates/bounce-classify",
  "crates/cidr-map",
  "crates/domain-map",
  "crates/integration-tests",
  "crates/kcli",
  "crates/kumod",
  "crates/mailparsing",
  "crates/mta-sts",
  "crates/proxy-server",
  "crates/rfc5321",
  "crates/spool",
  "crates/tailer",
  "crates/timeq",
  "crates/throttle",
  "crates/traffic-gen",
  "crates/tsa-daemon",
  "crates/libunbound-sys",
  "crates/validate-shaping",
  "crates/version-info",
]
resolver = "2"

[profile.release]
opt-level = 3
debug = 1 # include line tables for more meaningful backtraces

[workspace.dependencies]
axum = "0.6"
axum-server = "0.5"
data-encoding = "2.4"
ed25519-dalek = "2.0"
futures = "0.3.28"
mlua = "0.8"
once_cell = "1.17"
openssl = { version="0.10.57" }
openssl-sys = { version="0.9" }
rustls = "0.21"
tempfile = "3.8"
tokio = "1.32"
tokio-rustls = "0.24"
# Be sure to update the link to the docs in docs/reference/kumo.dns/configure_resolver.md
# to match the version that we are using when you update this dep
trust-dns-resolver = "0.23"
uuid = "1.4"
webpki-roots = "0.25"

[patch.crates-io]
# Can be removed once dane support is upstreamed
openssl = { version="0.10.57", git="https://github.com/KumoCorp/rust-openssl.git", branch="dane" }
# Can be removed once dane support is upstreamed
openssl-sys = { version="0.9", git="https://github.com/KumoCorp/rust-openssl.git", branch="dane" }
