[workspace]
members = [
  "crates/bounce-classify",
  "crates/kumod",
  "crates/rfc5321",
  "crates/spool",
  "crates/timeq",
  "crates/throttle",
  "crates/traffic-gen",
]
resolver = "2"

[profile.release]
opt-level = 3
# debug = 2

