[workspace]
members = [
  "crates/bounce-classify",
  "crates/cidr-map",
  "crates/domain-map",
  "crates/integration-tests",
  "crates/kcli",
  "crates/kumod",
  "crates/mailparsing",
  "crates/proxy-server",
  "crates/rfc5321",
  "crates/spool",
  "crates/tailer",
  "crates/timeq",
  "crates/throttle",
  "crates/traffic-gen",
  "crates/tsa-daemon",
  "crates/validate-shaping",
  "crates/version-info",
]
resolver = "2"

[profile.release]
opt-level = 3
debug = 1 # include line tables for more meaningful backtraces

[workspace.dependencies]
axum = "0.6"
axum-server = "0.5"
data-encoding = "2.4"
ed25519-dalek = "1.0.1"
mlua = "0.8"
rustls = "0.21"
tokio = "1.32"
tokio-rustls = "0.24"
trust-dns-resolver = "0.22" # can't upgrade to 0.23 due to mail-auth using 0.22
