[package]
name = "cfdkim"
version = "0.3.0"
authors = ["Sven Sauleau <sven@cloudflare.com>"]
edition = "2021"
description = "DKIM (RFC6376) implementation"
repository = "https://github.com/cloudflare/dkim"
documentation = "https://docs.rs/cfdkim"
categories = ["email"]
keywords = ["email", "dkim", "authentification"]
readme = "README.md"
license = "MIT"

[dependencies]
base64 = "0.21.0"
chrono = { version = "0.4.26", default-features = false, features = ["clock", "std"] }
ed25519-dalek = "1.0.1"
futures = "0.3.28"
indexmap = "1.9.3"
mailparse = "0.14"
memchr = "2.5"
nom = "7.1.0"
once_cell = "1.17"
quick-error = "2.0.1"
rsa = "0.9"
sha-1 = { version = "0.10", features = ["oid"] }
sha2 = { version = "0.10", features = ["oid"] }
tracing = "0.1"
trust-dns-resolver = "0.22"

[dev-dependencies]
tokio = { version = "1.25", features = ["macros"] }
regex = "1"
criterion = "0.3"

[[bench]]
name = "sign"
harness = false
