# THIS FILE IS FOR COMMUNITY CONTRIBUTED BOUNCE CLASSIFICATION RULES
# THESE ARE PROVIDED AS-IS BY THEIR RESPECTIVE CONTRIBUTERS
# THIS FILE SHOULD BE USED IN COMBINATION WITH shaping.toml TO GET FULL
# COVERAGE INCLUDING STATUS CODE BASED RULES.

# THIS FILE IS OVERWRITTEN DURING UPDATES, IF YOU MAKE CHANGES TO THIS FILE
# YOU WILL NEED TO DO A PULL REQUEST TO THE REPO AND HAVE IT ACCEPTED FOR 
# YOUR CHANGES TO PERSIST, OTHERWISE MAKE THESE CHANGES TO YOUR OWN CUSTOM
# SHAPING FILE:
# -- load the community shaping.toml + local settings
# kumo.on(
#  'get_egress_path_config',
#  shaping:setup {
#  '/opt/kumomta/share/policy-extras/shaping.toml',
#  '/opt/kumomta/share/community/shaping.toml`, 
#  '/opt/kumomta/etc/policy/custom-shaping.toml', 
#  }
# )

# kumo.on(
#  'get_egress_path_config',
#  shaping:setup { 
#  '/opt/kumomta/share/policy-extras/shaping.toml',
#  '/opt/kumomta/share/community/shaping.toml`, 
#  '/opt/kumomta/etc/policy/custom-shaping.toml',
#  }
# )