[package]
name = "mod-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = {path="../config"}
humantime = "2.1"
mail-builder = "0.2"
mailparse = "0.14"
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
reqwest = {workspace=true, default-features=false, features=["rustls-tls"]}
serde = {version="1.0", features=["derive"]}
