[package]
name = "dns-resolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
arc-swap = "1.6"
kumo-log-types = {path="../kumo-log-types"}
lazy_static = "1.4"
lruttl = {path="../lruttl"}
serde = {version="1.0", features=["derive"]}
tokio = {workspace=true}
tracing = "0.1"
trust-dns-resolver = {workspace=true}

[dev-dependencies]
k9 = "0.11"
