[package]
name = "config"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
lazy_static= "1.4"
metrics = "0.20"
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
tokio = {version="1.25", features=["fs"]}

[build-dependencies]
git2 = { version = "0.16", default-features = false }
