[package]
name = "mod-digest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = {path="../config"}
data-encoding = "2.4"
mlua = {version="0.8", features=["serialize"]}
ring = "0.16"
serde_json = "1.0"
