[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
axum = "0.6"
axum-server = "0.4"
k9 = "0.11"
kumo-log-types = {path="../kumo-log-types"}
lipsum = "0.8"
mail-builder = "0.2"
maildir = {git="https://github.com/wez/maildir.git", rev="898d604fec05bfcb5af52f3960c4b07028faad39"}
mailparse = "0.14"
nix = {version="0.26", features=["signal"]}
rfc5321 = {path="../rfc5321"}
serde_json = "1.0"
tempfile = "3.4"
textwrap = "0.16"
tokio = {version="1.25", features=["full"]}
zstd = "0.12"
