["default"]
enable_tls = "OpportunisticInsecure"

[["default".automation]]
regex = "you said 450-go-away"
action = "Suspend"
duration = "1 hour"

[["default".automation]]
regex = "you said 450-suspend-campaign"
action = "SuspendCampaign"
duration = "1 hour"
