[package]
name = "kumod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = {version="4.1", features=["derive"]}
lazy_static = "1.4"
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
tokio = {version="1.25", features=["full"]}
tracing = "0.1"
tracing-subscriber = {version="0.3", features=["env-filter"]}

[dev-dependencies]
k9 = "0.11"
