[package]
name = "kumod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-channel = "1.8"
axum = "0.6"
axum-client-ip = "0.4"
axum-server = {version="0.4", features=["tls-rustls"]}
base64 = "0.13"
bounce-classify = {path="../bounce-classify"}
caps = "0.5"
chrono = {version="0.4", features=["serde"]}
cidr = {version="0.2", features=["serde"]}
clap = {version="4.1", features=["derive"]}
config = {path="../config"}
data-loader = {path="../data-loader"}
domain-map = {path="../domain-map"}
gcd = "2.3"
gethostname = "0.4"
lazy_static = "1.4"
lruttl = {path="../lruttl"}
mail-auth = "0.3"
mail-builder = "0.2"
message = {path="../message"}
metrics = "0.20"
metrics-prometheus = "0.3"
metrics-tracing-context = "0.13"
minijinja = {version="0.30",features=["source"]}
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
mod-redis = {path="../mod-redis"}
mod-sqlite = {path="../mod-sqlite"}
nix = "0.26"
once_cell = "1.17"
ouroboros = "0.15"
prometheus = "0.13"
rand = "0.8"
rcgen = "0.10"
rfc5321 = {path="../rfc5321"}
rustls = "0.20"
rustls-pemfile = "1.0"
serde = {version="1.0", features=["derive"]}
humantime-serde = "1.1"
serde_json = "1.0"
spool = {path="../spool"}
thiserror = "1.0"
throttle = {path="../throttle"}
timeq = {path="../timeq"}
tokio = {version="1.25", features=["full"]}
tokio-rustls = "0.23"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = {version="0.3", features=["env-filter", "std", "fmt", "json"]}
trust-dns-resolver = "0.22"
webpki-roots = "0.22"
zstd = "0.12"

[dev-dependencies]
k9 = "0.11"
mail-parser = "0.8"
maplit = "1.0"
