[package]
name = "kumod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-channel = "1.8"
async-recursion = "1.0"
async-trait = "0.1"
axum = "0.6"
axum-client-ip = "0.4"
axum-server = {version="0.4", features=["tls-rustls"]}
backtrace = "0.3"
base64 = "0.13"
bounce-classify = {path="../bounce-classify"}
caps = "0.5"
cgroups-rs = "0.3"
chrono = {version="0.4", default-features=false, features=["serde"]}
cidr-map = {path="../cidr-map"}
clap = {version="4.1", features=["derive"]}
config = {path="../config"}
console-subscriber = "0.1"
data-loader = {path="../data-loader"}
dns-resolver = {path="../dns-resolver"}
domain-map = {path="../domain-map"}
gcd = "2.3"
gethostname = "0.4"
humansize = "2.1" # for printing
json_comments = "0.2"
tikv-jemallocator = "0.5"
tikv-jemalloc-sys = {version="0.5", features=["profiling", "unprefixed_malloc_on_supported_platforms"]}
kumo-api-types = {path="../kumo-api-types"}
kumo-log-types = {path="../kumo-log-types"}
lazy_static = "1.4"
lruttl = {path="../lruttl"}
mail-auth = "0.3"
mail-builder = "0.2"
maildir = {git="https://github.com/wez/maildir.git", rev="898d604fec05bfcb5af52f3960c4b07028faad39"}
memchr = "2.5"
message = {path="../message"}
metrics = "0.20"
metrics-prometheus = "0.3"
metrics-tracing-context = "0.13"
minijinja = {version="0.34",features=["source"]}
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
mod-amqp = {path="../mod-amqp"}
mod-dns-resolver = {path="../mod-dns-resolver"}
mod-http = {path="../mod-http"}
mod-memoize = {path="../mod-memoize"}
mod-redis = {path="../mod-redis"}
mod-sqlite = {path="../mod-sqlite"}
nix = {version="0.26", features=["resource"]}
once_cell = "1.17"
ppp = "2.2"
prometheus = "0.13"
rand = "0.8"
rcgen = "0.10"
rfc5321 = {path="../rfc5321"}
rustls = "0.20"
rustls-pemfile = "1.0"
serde = {version="1.0", features=["derive"]}
humantime-serde = "1.1"
self_cell = "1.0"
serde_json = "1.0"
socksv5 = {version="0.3", default-features=false, features=["tokio"]}
spool = {path="../spool"}
thiserror = "1.0"
throttle = {path="../throttle"}
timeq = {path="../timeq"}
tokio = {version="1.25", features=["full", "tracing"]}
tokio-rustls = "0.23"
toml = "0.7"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = {version="0.3", features=["env-filter", "std", "fmt", "json"]}
uuid = {version="1.3", features=["v4", "fast-rng"]}
version-info = {path="../version-info"}
webpki-roots = "0.22"
zstd = "0.12"

[dev-dependencies]
k9 = "0.11"
mail-parser = "0.8"
maplit = "1.0"
