[package]
name = "kumod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-channel = "1.8"
clap = {version="4.1", features=["derive"]}
gethostname = "0.4"
lazy_static = "1.4"
mail-auth = "0.3"
mail-send = "0.3"
message = {path="../message"}
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
ringbuf = "0.3"
rustls = "0.20"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
smtp-proto = "0.1"
spool = {path="../spool"}
thiserror = "1.0"
timeq = {path="../timeq"}
tokio = {version="1.25", features=["full"]}
tokio-rustls = "0.23"
tracing = "0.1"
tracing-subscriber = {version="0.3", features=["env-filter"]}
webpki-roots = "0.22"

[dev-dependencies]
k9 = "0.11"
