[package]
name = "tsa-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
axum = "0.6"
axum-client-ip = "0.4"
axum-server = {version="0.4", features=["tls-rustls"]}
chrono = {version="0.4", default-features=false, features=["serde"]}
clap = {version="4.1", features=["derive"]}
config = {path="../config"}
dns-resolver = {path="../dns-resolver"}
kumo-api-types = {path="../kumo-api-types"}
kumo-log-types = {path="../kumo-log-types"}
kumo-server-common = {path="../kumo-server-common"}
kumo-server-memory = {path="../kumo-server-memory"}
kumo-server-runtime = {path="../kumo-server-runtime"}
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
rfc5321= {path="../rfc5321"}
serde = {version="1.0", features=["derive"]}
tikv-jemalloc-sys = {version="0.5", features=["profiling", "unprefixed_malloc_on_supported_platforms"]}
tikv-jemallocator = "0.5"
tokio = {version="1.25", features=["full", "tracing"]}
tokio-rustls = "0.23"
toml = "0.7"
tracing = "0.1"
version-info = {path="../version-info"}
