[package]
name = "mod-string"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
config = {path="../config"}
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
psl = "2.1.46"
