[package]
name = "spool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
getrandom = "0.2"
jwalk = "0.8"
lazy_static = "1.4"
libc = "0.2.139"
mac_address = "1.1"
once_cell = "1.17"
rocksdb = {version="0.20", features=["jemalloc"]}
tempfile = "3.3"
tokio = {version="1.25", features=["sync", "rt", "fs", "macros", "tracing"]}
uuid = {version="1.3", features=["v1", "rng"]}
