[package]
name = "spool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
jwalk = "0.8"
libc = "0.2.139"
tempfile = "3.3"
tokio = {version="1.25", features=["sync", "rt", "fs", "macros"]}
uuid = {version="1.3", features=["v4", "fast-rng"]}
