[package]
name = "rfc5321"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5"
pest_derive = "2.5"
serde = {version="1.0", features=["derive"]}
thiserror = "1.0"
tokio = {version="1.25", features=["full"]}
tokio-rustls = {version="0.23", features=["dangerous_configuration"]}
webpki-roots = "0.22"
