[package]
name = "timeq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hierarchical_hash_wheel_timer = {version="1.1", default-features=false, features=["fx-hash"], git="https://github.com/wez/rust-hash-wheel-timer.git", branch="dont_panic"}
