[package]
name = "message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bitflags = "1.3"
chrono = {version="0.4", features=["serde"]}
futures = "0.3"
lazy_static = "1.4"
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
prometheus = "0.13"
rand = "0.8"
rfc5321 = {path="../rfc5321"}
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
spool = {path="../spool"}
timeq = {path="../timeq"}
tokio = {version="1.25", features=["sync"]}
