[package]
name = "mod-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
config = {path="../config"}
json_comments = "0.2"
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
serde_json = "1.0"
serde_yaml = "0.9"
tokio = {workspace=true, features=["fs"]}
toml = "0.8"
