[package]
name = "mod-dns-resolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = {path="../config"}
dns-resolver = {path="../dns-resolver"}
mlua = {version="0.8", features=["vendored", "lua54", "async", "send", "serialize"]}
tokio = {version="1.25", features=["rt"]}
