[package]
name = "tls-probe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = {version="4.5", features=["derive"]}
env_logger = "0.11"
kumo-api-types = {path="../kumo-api-types"}
log = "0.4"
rfc5321 = {path="../rfc5321"}
tokio = {workspace=true, features=["full"]}
tracing = {version="0.1", features=["log"]}
