[package]
name = "mailparsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3"
charset = "0.1"
data-encoding = "2.4"
nom = "7.1"
nom_locate = "4.1"
nom-tracable = "0.9"
paste = "1.0"
pest = "2.5"
pest_derive = "2.5"
quoted_printable = "0.5"
textwrap = "0.16"
thiserror = "1.0"

[features]
trace = ["nom-tracable/trace"]

[dev-dependencies]
k9 = "0.11"
