[package]
name = "mailparsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3"
charset = "0.1"
data-encoding = "2.4"
pest = "2.5"
pest_derive = "2.5"
quoted_printable = "0.4"
thiserror = "1.0"

[dev-dependencies]
k9 = "0.11"
