[package]
name = "mailparsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3"
charset = "0.1"
data-encoding = "2.4"
data-encoding-macro = "0.1"
memchr = "2.5"
nom = "7.1"
nom_locate = "4.1"
paste = "1.0"
quoted_printable = "0.5"
textwrap = "0.16"
thiserror = "1.0"

[dev-dependencies]
k9 = "0.11"
