[package]
name = "throttle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
mod-redis = {path="../mod-redis"}
once_cell = "1.17"
redis-cell-impl = { git = "https://github.com/wez/redis-cell.git", rev="97d409c3a62f2a0f5518c31fc9b4b65afbce2053" }
serde = {version="1.0", features=["derive"]}
thiserror = "1.0"
tokio = {version="1.25", features=["full"]}
uuid = {version="1.3", features=["v4", "fast-rng"]}
