[package]
name = "kcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = {version="4.1", features=["derive"]}
humantime = "2.1"
kumo-api-types = {path="../kumo-api-types"}
reqwest = {version="0.11", default-features=false, features=["json", "rustls-tls"]}
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
tokio = {version="1.25", features=["full", "tracing"]}
version-info = {path="../version-info"}
