name: Check code formatting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Install Rust"
      uses: actions-rs/toolchain@v1
      with:
        profile: "minimal"
        toolchain: "nightly"
        default: true
        override: true
        components: "rustfmt"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-mdbook-${{ hashFiles('.github/workflows/fmt.yml') }}
    - name: Rust formatting
      run: |
        source $HOME/.cargo/env
        cargo +nightly fmt --all -- --check
    - name: Lua formatting
      run: |
        source $HOME/.cargo/env
        cargo install stylua --features lua54
        stylua --check --config-path stylua.toml .
        cargo test --verbose
