name: pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/pages.yml"
  #schedule:
  #  - cron: "50 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pages-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mdBook
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook
          features: search
          args: --locked
      - name: Install mdBook-linkcheck
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-linkcheck
          args: --locked
      - name: Install mdBook-mermaid
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-mermaid
          args: --locked
      - name: Install mdBook-admonish
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-admonish
          args: --locked
      - name: Install gelatyx
        uses: baptiste0928/cargo-install@v1
        with:
          crate: gelatyx
          args: --locked
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./docs/build.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: gh_pages/html

  pages-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: pages-build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
