name: Publish Builder Images

on:
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build images
        run: python3 assets/ci/build-builder-images.py ghcr.io
