name: Publish Package Repos

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/publish-pkg-repos.yml"
      - "assets/yum.repos.d/*.repo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Publish"
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        TOKEN: ${{ secrets.OPENREPO_API_TOKEN }}
      shell: bash
      run: |
        ./assets/upload-package.sh files assets/yum.repos.d/*.repo

