name: Publish Builder Images

on:
  workflow_dispatch:
  schedule:
    # Weekly rebuild
    - cron: "15 2 * * 0"


jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "ubuntu:20.04"
          - "ubuntu:22.04"
          - "rockylinux:8"
          - "rockylinux:9"
          - "amazonlinux:2"
          - "amazonlinux:2023"

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: python3 assets/ci/build-builder-images.py ghcr.io ${{ matrix.image }}
