name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "crates/**/*.rs"
      - ".github/workflows/rust.yml"
      - "**/Cargo.toml"

  pull_request:
    branches: [ "main" ]
    paths:
      - "crates/**/*.rs"
      - ".github/workflows/rust.yml"
      - "**/Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install cargo-nextest
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-nextest
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo nextest run
