name: Rust

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "docs/*"
      - ".github/workflows/pages.yml"
      - ".github/workflows/verify-pages.yml"
      - ".github/ISSUE_TEMPLATE/*"
      - "**/*.md"
      - "**/*.markdown"

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "docs/*"
      - ".github/workflows/pages.yml"
      - ".github/workflows/verify-pages.yml"
      - ".github/ISSUE_TEMPLATE/*"
      - "**/*.md"
      - "**/*.markdown"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install cargo-nextest
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-nextest
        args: --locked
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo nextest run
