name: verify-pages

on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/verify-pages.yml"

jobs:
  verify-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mdBook
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook
          features: search
          locked: true
      - name: Install mdBook-linkcheck
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-linkcheck
          locked: true
      - name: Install mdBook-mermaid
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-mermaid
          locked: true
      - name: Install mdBook-admonish
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-admonish
          locked: true
      - name: Install gelatyx
        uses: baptiste0928/cargo-install@v1
        with:
          crate: gelatyx
          locked: true
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./docs/build.sh
